In [1]:
import numpy as np

### Exercícios

1. Crie um array unidimensional com números inteiros distribuídos de maneira aleatória de 1 a 100, e filtre apenas os números maiores ou iguais a 50.

In [2]:
arr = np.random.randint(1, 101, size=200)
arr[arr>=50]

array([ 54,  59,  51,  67,  50,  83, 100,  91,  66,  60,  89,  84,  61,
        73,  61,  89,  55,  88,  65,  77,  77,  57,  91,  70,  89,  92,
        79,  83,  81,  87,  87,  82,  98,  86,  99,  95,  91,  79,  83,
        70,  73, 100,  53,  57,  64,  85,  87, 100,  74,  76,  56,  68,
        60,  51,  53,  86,  93,  99,  71, 100,  65,  88,  59,  92,  60,
        91,  97,  76,  68,  94,  56,  99,  95,  92,  98,  74,  85,  65,
        85,  75,  66,  69,  97,  68,  77,  70,  55,  67,  92,  97,  64,
        70,  80,  55,  69,  82,  78,  63,  90,  69,  86,  59,  82, 100,
        69])

2. Crie um array 1-dimensional (com 100 elementos) com números reais (float) aleatórios, e retorne as seguintes métricas:
  - média
  - mediana
  - desvio padrão
  - máximo
  - mínimo
  - índice do elemento máximo
  - indice do elemento mínimo

In [3]:
aleatorio2 = np.random.rand(100)
print(aleatorio2)

[0.18363131 0.93378753 0.07038418 0.33436443 0.34439869 0.4885653
 0.80746074 0.31827812 0.15557028 0.1265393  0.44918572 0.18277544
 0.79348331 0.5606046  0.34896424 0.68292305 0.34913408 0.76710806
 0.19752334 0.47711467 0.88802866 0.84785698 0.33610877 0.7412153
 0.48886588 0.06509676 0.04669313 0.46912601 0.83848452 0.54694923
 0.17577613 0.49795229 0.45386552 0.64012267 0.0091632  0.47916899
 0.7871906  0.60673394 0.2140739  0.16196452 0.97111843 0.893348
 0.69753455 0.66885817 0.91756309 0.80416005 0.86334267 0.71841983
 0.23302379 0.77239806 0.04505279 0.9898365  0.02811802 0.70070672
 0.68614115 0.09524395 0.7460527  0.966735   0.56751185 0.72520262
 0.01032686 0.07089597 0.31778126 0.43005889 0.75745421 0.5316689
 0.49175423 0.79447805 0.14001945 0.47054676 0.17756816 0.48475141
 0.30787395 0.29780602 0.68713771 0.38141023 0.92700932 0.92701633
 0.13403904 0.04605793 0.67013184 0.82616403 0.46417715 0.4688134
 0.93681927 0.61664156 0.65711912 0.28196013 0.49725954 0.58975425
 

In [4]:
print(f"Média: {aleatorio2.mean()}")
print(f"Mediana: {np.median(aleatorio2)}")
print(f"Desvio Padrão: {aleatorio2.std()}")
print(f"Máximo: {aleatorio2.max()}")
print(f"Mínimo: {aleatorio2.min()}")
print(f"Índice Min: {aleatorio2.argmin()}")
print(f"Índice Max: {aleatorio2.argmax()}")

Média: 0.4884022937806916
Mediana: 0.4840086571703195
Desvio Padrão: 0.2836719066370332
Máximo: 0.9898364957668305
Mínimo: 0.009163203455200053
Índice Min: 34
Índice Max: 51


3. Crie uma array 2-dimensional (10x5) com números reais (float) aleatórios, e retorne as seguintes métricas:
  - média
  - mediana
  - desvio padrão
  - máximo
  - mínimo
  - índice do elemento máximo
  - indice do elemento mínimo

In [5]:
aleatorio3 = np.random.rand(50)
matriz = aleatorio3.reshape((10, 5))
print(matriz)

[[0.26626798 0.79105681 0.25038414 0.60875052 0.31278833]
 [0.5563957  0.09771779 0.94120998 0.73790756 0.3935912 ]
 [0.81107742 0.3308445  0.75442952 0.23523295 0.10532411]
 [0.55168952 0.60164674 0.92641222 0.24259033 0.20423563]
 [0.04943053 0.74990211 0.93032775 0.18043136 0.07165401]
 [0.36466147 0.52897282 0.54281116 0.02111287 0.87515658]
 [0.06385711 0.15305854 0.20336162 0.61089755 0.04883536]
 [0.17815647 0.26442859 0.00978165 0.78869312 0.24999316]
 [0.746672   0.40320322 0.24571864 0.7850618  0.52718804]
 [0.54679422 0.25719753 0.14319406 0.94920464 0.41831345]]


In [6]:
print(f"Média: {matriz.mean()}")
print(f"Mediana: {np.median(matriz)}")
print(f"Desvio Padrão: {matriz.std()}")
print(f"Máximo: {matriz.max()}")
print(f"Mínimo: {matriz.min()}")
print(f"Índice Max: {matriz.argmax()}")
print(f"Índice Min: {matriz.argmin()}")

Média: 0.43255248722736006
Mediana: 0.37912633661318623
Desvio Padrão: 0.28684472571395814
Máximo: 0.9492046398592178
Mínimo: 0.009781650361271654
Índice Max: 48
Índice Min: 37


4. Crie um array 1-dimensional com 100 inteiros aleatórios de 0 a 1000, e substitua cada valor ímpar por -1.

In [7]:
arr4 = np.random.randint(0, 1001, size=100)
print(arr4)

[273 270 411 976  85 197 369 194 924 303 957 858 492 480 416 571 608 585
 973   0 783 238 748 880 518  11   1 907 579 233 190 622 153 781 513 634
 406 155 232 415 327 947 563 693 615 864 528 670 850 752 363 912 558 929
 170 511 790 192 150 264 814 796 777 867 478 752 288 321 732 432 128 918
  84 310 617 111 362  10 519 885 569 453  29 553 762 809 862 532 662 718
  34  62 552 474 658 564 207 803 604 414]


In [8]:
arr4[arr4 % 2 != 0] = -1
print(arr4)

[ -1 270  -1 976  -1  -1  -1 194 924  -1  -1 858 492 480 416  -1 608  -1
  -1   0  -1 238 748 880 518  -1  -1  -1  -1  -1 190 622  -1  -1  -1 634
 406  -1 232  -1  -1  -1  -1  -1  -1 864 528 670 850 752  -1 912 558  -1
 170  -1 790 192 150 264 814 796  -1  -1 478 752 288  -1 732 432 128 918
  84 310  -1  -1 362  10  -1  -1  -1  -1  -1  -1 762  -1 862 532 662 718
  34  62 552 474 658 564  -1  -1 604 414]
